### ISSUE TITLE
rename all 3 cert.pem, chain.pem and fullchain.pem to .pem-revoked

### ISSUE THREAD

**Issue by gertcuykens** [lukas2511/dehydrated#238]
If one of them is being revoked all three of them are invalid.

**Comment by lukas2511** [comment]
Since the revoke command can also be used with certificates that have been installed somewhere else or certificates that have been generated using the `--signcsr` command it would be a bit complicated to do this, and in some rare cases it may even break something. Also I don't really see a requirement for this, if you are revoking cert.pem and running the script again it will notice the cert missing, will sign it again, and will rotate all other files as well.
