### ISSUE TITLE
Anyone experience with gandi as DNS server? (The txt record is not updated fast enough)

### ISSUE THREAD

**Issue by athei** [lukas2511/dehydrated#308]
I manage my zones at gandi.net. When I add an txt record it takes ages until the authoritative name servers adjust to the new zone (I use their DNS servers). I guess they have a very long reload interval. I am waiting for 30 minutes for the TXT record to show up and its still not there. Not really useable with letsencrypt. Does anyone use this provider with the DNS challenge and found some workaround or am I doing it wrong?

**Comment by txr13** [comment]
You need to adjust the TTL on your SOA record. Having a low TTL on the TXT records themselves will help, but because you're needing the nameservers to pick up on new records, that refresh time will be controlled by the SOA on the zone. Not all providers will allow you to modify that (easyDNS does allow it; Namecheap and GoDaddy do not, for example).

FWIW, Namecheap in particular uses a 30 minute refresh time, and even so always manages to ignore one of the new records I attempt to upload. If I upload N records, it only populates N-1 records, and I have to wait another 30 minutes refresh time to get the last record uploaded correctly. I will emphasize that dehydrated and Let's Encrypt both still work with this hindrance! It's damnably annoying, but it does work... eventually.

(Though GoDaddy also does not allow you to modify the SOA on the zone, it has a much faster refresh time, and accepts all records uploaded. Which makes it less problematic.)
