### ISSUE TITLE
cert specific config not loaded if wellknown does not exists

### ISSUE THREAD

**Issue by Lem** [lukas2511/dehydrated#314]
Under the following circumstances certificate specific config file will not be loaded:

- Using http-01 in `$SCRIPTDIR/config` (e.g using default config from `docs/examples/config`)
- WELLKNOWN-dir does not exists
- certificate specific config file placed in `certs/domain.tld/config`

```
root@host:/tmp# /root/dehydrated/dehydrated -c -d domain.tld
# INFO: Using main config file /root/dehydrated/config
ERROR: WELLKNOWN directory doesn't exist, please create /var/www/dehydrated and set appropriate permissions.
```

Even if the certificate specific config is using dns-01 it seems to be odd to enforce an existing WELLKNOWN-dir. Creating it is a simple workaround if you're using dns-01 only.

**Comment by lukas2511** [comment]
Well this is a bit more complicated to "fix", I need to verify the config because there are parameters which may influence loading of additional config files, and I don't really want to split it up. Since the additional config files were intended to only be used in special cases I still see the requirement of the main configuration being valid.
