### ISSUE TITLE
Checking certificate status after running dehydrated -c

### ISSUE THREAD

**Issue by mavrekh** [lukas2511/dehydrated#372]
Hi,

I have dehydrated running as a cron process with the -c option and I need the process to send out an email whenever a new certificate is successfully obtained: i.e. no "Valid till ... Skipping renew" message, but also no 500 errors from letsencrypt, no issues writing to the .well-known dir, etc. What is the best way the check whether a new certificate has been obtained after running dehydrated? I guess one way would be to grep through the output and look for something like "Done!", but I'd like something more failsafe.

Thanks!

Misha

**Comment by txr13** [comment]
I personally have a small script for this purpose. It goes through all my certs and compares the SHA-1 hash of the current fullchain.pem to the previous value. If the hash has changed, it fires whatever update is needed for that particular certificate.

You may also be able to use the deploy_cert hook for this purpose, since that is "called once for each certificate that has been produced."

**Comment by mavrekh** [comment]
Would you mind sharing the hash comparison script, or at least the relevant parts?

**Comment by txr13** [comment]
I don't mind at all. I've uploaded it [here](https://github.com/lukas2511/dehydrated/files/865947/update-certs.txt) for your convenience.

Basically, it loops over all certificate directories in `CERTDIR`. In each directory, it calculates the current hash for private key and fullchain, checks for the previously-saved hash for the private key and fullchain, and determines whether those files have changed.

If a change is found, then we check the certificate directory for a per-certificate override file telling us what actions to take. If found, execute that script. Otherwise, we perform the default actions. Then we fire off an email notifying us of what needs to be done, save the new hash values to the certificate directory, and move on.

Additional points of note:
- this script assumes that a change in the main certificate file is enough to trigger a set of actions, regardless of whether the private key changed or not. If you need other actions to be taken depending on whether the private key also changed, you'll need to move that check up accordingly.
- if you don't care about whether the private key updated (for example, if you have set `PRIVATE_KEY_RENEW="yes"` and don't have that overridden anywhere, then you can remove the checks for private key hash and the second email completely.

**Comment by mavrekh** [comment]
Thank you so much! This is really helpful.

**Comment by lukas2511** [comment]
I'd recommend using the `deploy_cert` hook for this like @txr13 already mentioned.

**Comment by mavrekh** [comment]
Yes, I ended up implementing a deploy_cert hook and it works great. Sorry for not closing this earlier, and thanks so much for your help.
