### ISSUE TITLE
--cleanup from hook

### ISSUE THREAD

**Issue by bax-** [lukas2511/dehydrated#389]
is it possible to call `dehydrated --cleanup` from within a hook, e.g. `exit_hook`?

**Comment by lukas2511** [comment]
I implemented a feature for this in e6d6882c78c3f91ad6e296c058063a01a35c1a3d. Just set `AUTO_CLEANUP="yes"` in your config and it will run the cleanup routine before `exit_hook`. Otherwise (if you really need to do it manually) you can force dehydrated to use a different lockfile, but I don't recommend doing that.
