### ISSUE TITLE
Crontab

### ISSUE THREAD

**Issue by dulemis** [lukas2511/dehydrated#403]
Having an issue with crontab. On the command line everything works, but in crontab the ouput of the same command is :

To use dehydrated with this certificate authority you have to agree to their terms of service which you can find here: https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf

To accept these terms of service run `/jffs/LetsEncrypt/dehydrated --register --accept-terms`.

However, I have already run the command with --register --accept-terms.

**Comment by lukas2511** [comment]
For me it seems that dehydrated is using a different config / path than when you initially ran it.

I'd recommend setting the paths in a config file and tell your cronjob which config to use, just to be sure. 

Normally this isn't necessary, but without any more information I have no idea what is wrong with your specific setup. Closing this issue for now since this seems like just a user error to me.

**Comment by dulemis** [comment]
I also thought so, but I have tried running it with the -c flag to use the same config (which isn't needed when running it from the shell), but it returns the same. Any further ideas?

I m running it on a Linux embedded router, probably nbothing special.

**Comment by txr13** [comment]
@dulemis The `-c` option is the command for cron mode. You'll want to try using the `-f` flag to specify the location of your config file.

**Comment by dulemis** [comment]
Sorry, I meant --config.
Im redirecting the cron output to a textfile,  and it logs at the top that its using the correct config. However, it still acts like its The first run...

**Comment by dulemis** [comment]
Anyone having an idea why dehydrated thinks i'm running it for the first time in cron? I have specified the --config parameter, and everything works on the command line...

**Comment by dulemis** [comment]
No one..?
