### ISSUE TITLE
Write certificate even if chain is not downloaded

### ISSUE THREAD

**Issue by lukavia** [lukas2511/dehydrated#405]
I have a machine that is not allowed to make outbound connections on port 80. 
443 is working fine. 
As a result, when dehydrated runs, it goes through all the steps and issues the certificate, but then it tries to download the chain before saving/moving the files in place and curl fails. 
Then on consequential runs, since it doesn't find the issued certificate it reissues it, but it fails again. 

This leads to quickly reaching domain limit of 20 for 7 days and blocks any other subdomains for issuing new certificates. 

I suggest the cert file to be written write after it is downloaded and moved in place. And then let the chain fail. That way unwanted reissuing of the certificate will be avoided

**Comment by lukas2511** [comment]
Mh... I've just implemented caching for certificate chains (see d685463673919ba4f9d2035d021293f241a66055), with that you could at least write the file manually and have the script working on the next run (error message gives instructions on where to get and place files).

Moving the certificate in place before everything else is ready is no option for me, I (and probably most of the scripts users) always use the fullchain.pem in combination with privkey.pem, so if cert.pem and privkey.pem would have been moved in position before fullchain.pem was generated this would result in tons of broken systems.

Does the cache fix your issue? Otherwise we might think about implementing a fixup-command, that looks for unlinked certs and keys, verifies that they are valid (ocsp), generates the chain and puts them into place, but this would be quite a lot of work for an edgecase like this...

**Comment by lukavia** [comment]
The cache would work great.
I would just install the chain with me initial & update routines. 
Thank you very much :)
