### ISSUE TITLE
Wrong default setting

### ISSUE THREAD

**Issue by K-Ko** [lukas2511/dehydrated#407]
`config.sh` says

    # Output directory for challenge-tokens to be served by webserver or deployed in HOOK (default: $BASEDIR/.acme-challenges)
    #WELLKNOWN=$BASEDIR/.acme-challenges

If I use a custom config file and **only** change `BASEDIR`, the default is calculated wrong:

    [[ -z "${WELLKNOWN}" ]] && WELLKNOWN="/var/www/dehydrated"

Must be

    [[ -z "${WELLKNOWN}" ]] && WELLKNOWN="${BASEDIR}"

So I have to change `WELLKNOWN=...` also

**Comment by lukas2511** [comment]
No, that's not an issue, you should **never** serve challenge files from your BASEDIR! Those files are to be considered **very** public and you should keep them as far away as possible from your private data.

Also you seem to have an old version of the example config since the new one clearly shows `/var/www/dehydrated` as default value:

```
# Output directory for challenge-tokens to be served by webserver or deployed in HOOK (default: /var/www/dehydrated)
#WELLKNOWN="/var/www/dehydrated"
```
