### ISSUE TITLE
*chain*.pem contains blank line and url

### ISSUE THREAD

**Issue by dannietjoh** [lukas2511/dehydrated#460]
The chain.pem and fullchain.pem (with and without timestamp) include a blank line and url, making my webserver (nginx) not like them, is this intentional?

here is an example fullchain.pem:
`-----BEGIN CERTIFICATE-----
MIIF/TCCBOWgAwIBAgISAxNTsyrquKu00NNY0jYD+FGyMA0GCSqGSIb3DQEBCwUA
....
-----END CERTIFICATE-----

http://cert.int-x3.letsencrypt.org/
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
.....
-----END CERTIFICATE-----
`

**Comment by txr13** [comment]
That’s as expected. NGINX handles it okay for me...

**Comment by lukas2511** [comment]
Yes this is intentional and shouldn't result in any problems, there probably is a different reason why your nginx doesn't "like" the certificates (bad permissions? missing semicolon in nginx config? etc.).

If removing (and readding, just to make sure) the url changes anything, please report which version of nginx you are using and which ssl library it's linked against.
