### ISSUE TITLE
this_hookscript_is_broken__dehydrated_is_working_fine__please_ignore_unknown_hooks_in_your_script

### ISSUE THREAD

**Issue by nkovacne** [lukas2511/dehydrated#490]
We just upgraded to the last version of dehydrated (prior version was: 4.0.X). After that, when running the script I see:

> [2018-03-07 11:03:01] Unknown command: this_hookscript_is_broken__dehydrated_is_working_fine__please_ignore_unknown_hooks_in_your_script

In the CHANGELOG I could find this:

> Calling random hook on startup to make it clear to hook script authors that unknown hooks should just be ignored...

The function that throws this message just checks whether the `HOOK` variable has any content and then it shows the message. I also understand that this is done on purpose, but I just can't understand the reason?

Will it be wrong to specify a hook from now on? In our case this hook does a lot of work in terms of integration with our DNS server so it is unthinkable to remove it. If this is the wrong way to go, is there any other recommended way to do this?

**Comment by lukas2511** [comment]
Dehydrated is constantly extended with new hook calls and existing hook scripts constantly break and I get tons of bug reports that dehydrated is broken.

Hook scripts should just ignore unknown hooks, that's why this hook breaker has been implemented.
It should make it clear to hook script authors to simply please_ignore_unknown_hooks to be compatible with future dehydrated versions.

If you are using somebody else's hook script please contact them to ignore all unknown hooks. If this is your script please make sure that you ignore unknown hooks.

**Comment by txr13** [comment]
@nkovacne The example hook script in the repo illustrates how to whitelist particular functions in a hook script. All others will be ignored.

If you implement something like that, and whitelist only the functions implemented by your hook script, the error will go away.

**Comment by nkovacne** [comment]
@txr13 Yep, in fact it was my fault. My hook file actually caught any undefined hook and sent to stdout the error message that I wrote in my first message (which I thought was sent by the dehydrated script). I simply removed the "echo" statement and it stopped showing up. Thanks.
