### ISSUE TITLE
Wildcard & Base Domain: Two TXTs

### ISSUE THREAD

**Issue by badfiles** [lukas2511/dehydrated#508]
This example became invalid since a wildcard request with base domain included needs two TXT records present at the same time. 
```
 # Simple example: Use nsupdate with local named
    # printf 'server 127.0.0.1\nupdate delete _acme-challenge.%s TXT "%s"\nsend\n' "${DOMAIN}" "${TOKEN_VALUE}" | nsupdate -k /var/run/named/session.key

```
https://community.letsencrypt.org/t/wildcard-base-domain-two-txts-timeout-problem/56105

**Comment by jobe1986** [comment]
That example is still perfectly valid. The hook script is called for EACH individual "token" value set for the TXT record, that example deletes only the TXT record with the supplied token value. So that example will be called once for each TXT record even if they are the same name.

I Currently use the nsupdate method with my setup for domain validations, and I have yet to have an issue with either TXT records remaining where they shouldn't or with TXT records being deleted when they shouldn't.

**Comment by lukas2511** [comment]
I also don't see how that code would be invalid, it only deletes exactly what it should delete.
