### ISSUE TITLE
Hook_chain being ignored

### ISSUE THREAD

**Issue by ryancbutler** [lukas2511/dehydrated#552]
Recently Dehydrated seems to be validating challenges only after all my deploy challenges have been run causing issues on approval.  Seems like HOOK_CHAIN value is being seen as YES.

I have **hook_chain** set to no in my config

domains are listed as 
mysub.domain.com mysub1.domain.com mysub2.domain.com

```
Dehydrated by Lukas Schauer
https://dehydrated.io

Dehydrated version: git-master-after-0.6.2
GIT-Revision: b5dddd7a2b64b1e035a1bd27aa5e699a304bdbca

OS: Ubuntu 16.04.3 LTS
Used software:
 bash: 4.3.48(1)-release
 curl: curl 7.47.0
 awk: GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)
 sed: sed (GNU sed) 4.2.2
 mktemp: mktemp (GNU coreutils) 8.25
 grep: grep (GNU grep) 2.25
 diff: diff (GNU diffutils) 3.3
 openssl: OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by lukas2511** [comment]
This works as intended. Because of problems with wildcard validations there isn't really any choice but to deploy all tokens before doing anything else. Since I wanted to avoid having multiple different behaviours this now is the way it works. Hook-Chaining is different in that it deploys all tokens in one hook-call, without chaining it's still one after another, just the validation is delayed.

**Comment by ryancbutler** [comment]
Oh bummer.  I had a process that would use the token to edit the same netscaler policy with the challenge token for every domain.  Any other options you can think of to mimic this behavior?

**Comment by lukas2511** [comment]
I don't really have any experience with Netscaler, but from a quick glance over your code you could just add multiple rules, or maybe there is a way to set up a reverse proxy or something? Otherwise you could maybe validate tokens over DNS-01 instead.
