### ISSUE TITLE
Discussion: Bad DNS provider APIs

### ISSUE THREAD

**Issue by lukas2511** [lukas2511/dehydrated#554]
Some DNS providers only allow a single TXT record per domain. This can currently result in problems when trying to use domain sets like `example.org *.example.org` where two challenges are verified on the same domain.

Please read [tbd] before commenting on this thread!!!!!!!

If (and only if!) you are using one of those providers and there is no way to fix your hook-script, your DNS-provider doesn't want to change their API and you can't easily change to a different DNS provider please leave a comment on this thread containing your DNS provider and a link to the API documentation so I can verify the issue.

Please also check if somebody else already commented with that provider and in that case just give that post a thumbs-up or something.

**Comment by wpyoga** [comment]
Hi, I have a workaround for this problem, with GoDaddy API. This provider does not let us add new TXT records with the same name, it always overwrites all existing records with the data from the latest PUT API call.

It's not perfect, because it creates a throwaway certificate in the process. So, without having to handle existing `_acme-challenge` records, we should have two lines in domains.txt:
```txt
*.example.com > example_com
*.example.com example.com > example_com
```

This works for simple personal servers, but will likely fail if the server has too many domains on it. What will happen is:
1. dehydrated will read the first line request a certificate with `CN=*.example.com`, and it will complete 1 single challenge
1. dehydrated will read the first line and checks the existing certificate, which has a different set of domains, so it will force a renew
1. dehydrated will request the new certificate, and it will receive 1 single challenge (because the domain `*.example.com` has been authorized recently)
1. certificate renewal will succeed

What do you guys think?

Notes: For GoDaddy, the proper solution requires a more advanced hook script. For some DNS providers like Duck DNS mentioned in #553 , this might be helpful... or not?

**Comment by marcomsousa** [comment]
duckdns.org only allow a single TXT record per domain.

Since my scenario are:
- a.example.com CNAME  b.duckdns.org 
- _acme-challenge.a.example.com CNAME _acme-challenge.b.duckdns.org

Since 0.6.0 if I execute dehydrated with two domains:
`dehydrated --cron --hook ./hooks.sh --challenge dns-01 --domain a.example.com --domain b.duckdns.org`
Dehydrated try to deploy the two challenge at the same time. Only after, will responding the challenge for both domains. (parallel)

I can only validate if I can force dehydrated to do sequential validations.
Deploy 1 challenge, validate 1 challenge, clean, deploy 2 challenge, validate 2 challenge, clean. (sequential).

**Comment by marcomsousa** [comment]
Our need is supported by https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode

**Comment by GimmeHardware** [comment]
Big fan of dehydrated, been using it for years. Thanks for a great tool!

But... this problem keeps biting me. Adding to the providers mentioned above,
  Hurricane Electric is affected (see description on their DNS home page https://dns.he.net).
  ZoneEdit is affected (https://support.zoneedit.com/en/knowledgebase/article/changes-to-dynamic-dns).

In the dehydrated repo, hook_chain.md still documents HOOK_CHAIN as handling exactly this problem, but is seems HOOK_CHAIN now actually does something different. So hook_chain.md should be updated or removed.

Also in your repo I see a "fix_dns_challenge_validation" branch where between dehydrated 0.65 and 0.70 you fixed it - first restored HOOK_CHAIN to the original documented behavior and then reverted that and instead added a new HOOK_SEQ feature to address this problem. But that branch was never merged and was left behind.

Comments here show people are switching from dehydrated to acme.sh or certbot because of this. Please reconsider fixing it.
