### ISSUE TITLE
adding certalias to deploy_cert ?

### ISSUE THREAD

**Issue by gytisgreitai** [lukas2511/dehydrated#556]
Right now the deploy_cert receives domain name, key, cert, fullchain path and date but not the alias (e.g. for wildcard certs)

Since `alias` variable is already exported, the change would be as simple as adding it to the end of command, and would not break any existing implementations:

`  [[ -n "${HOOK}" ]] && "${HOOK}" "deploy_cert" "${domain}" "${certdir}/privkey.pem" "${certdir}/cert.pem" "${certdir}/fullchain.pem" "${certdir}/chain.pem" "${timestamp}" "${alias}"`

**Comment by jobe1986** [comment]
You can also use a combination of the dirname and basename commands to extract the alias name from the key, cert, fullchain or chain paths.

I found this out when I considered making a similar request for the $certdir path to be added to the same hook but found I could work them out myself.

**Comment by lukas2511** [comment]
Like @jobe1986 said you can already extract that from the path and you could also just use the environment variable as it's exported.

**Comment by lcts** [comment]
For others who stumble on this issue:
If, like me, you prefer to extract the alias from the parameters passed to the hook, here's one simple way to get it from e.g. the keyfile (parameter $2):
```
certalias=$(_TMP=${2%/*};echo ${_TMP##*/})
```
(strip everything up to the first / from end of string (path), then strip everything up to the last / from beginning)
It doesn't matter what name you give `_TMP`, and if you're using the hook.sh template you can replace `${2%/*}` with `${KEYFILE%/*}` for better readability.
If your hook is executed in zsh instead of bash, this works:
```
certalias=${${2%/*}##*/}
```
