### ISSUE TITLE
Why was version 1 API removed

### ISSUE THREAD

**Issue by mrackers** [lukas2511/dehydrated#633]
We started getting errors 3/3/2019 related to version 1 not supported. We found that you removed that support in the code within the last day. Can you explain why?

**Comment by lukas2511** [comment]
This was discussed since quite a while ago, see #510. Main reason being that ACME v1 support always results in a bit more work and less easily readable code. Since ACME v2 has been around (and live) for quite a while now and is to be considered stable and without any drawbacks I didn't see any reason to keep the old protocol around.

If you are using Let's Encrypt infrastructure I'd recommend you change over to the ACME v2 endpoint, if you have a good use-case for keeping ACME v1 please tell me.

**Comment by lukas2511** [comment]
I was approached by another person telling me that there actually are other CAs out there that implemented v1 and not v2, so I reverted the removal for now and will keep v1 around for as long as there a no major inconveniences supporting it with future changes. I've written a bit about this in the the documentation so it doesn't become a surprise in the future see [docs/acme-v1.md](https://github.com/lukas2511/dehydrated/blob/74a536c16178312845503caa5322c19de34b2dca/docs/acme-v1.md).
